import * as stylex from "@stylexjs/stylex";
import { colors, radii, space, type } from "../tokens.stylex";

export const styles = stylex.create({
  page: { backgroundColor: colors.paper, color: colors.ink },
  wrap: {
    maxWidth: "760px",
    marginInline: "auto",
    paddingInline: { default: space.lg, "@media (max-width: 780px)": space.base },
  },
  wide: {
    maxWidth: "1100px",
    marginInline: "auto",
    paddingInline: { default: space.lg, "@media (max-width: 780px)": space.base },
  },
  // The hero is a specimen beside the headline, so it is a two-column grid that
  // stacks on a phone. The headline drops from 64px because it now shares the row.
  hero: {
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(0, 5fr) minmax(0, 6fr)",
      "@media (max-width: 780px)": "1fr",
    },
    gap: { default: "72px", "@media (max-width: 780px)": space.xl },
    alignItems: "center",
    paddingTop: { default: "96px", "@media (max-width: 780px)": space.xxl },
    paddingBottom: { default: "96px", "@media (max-width: 780px)": space.xl },
  },
  headline: {
    fontSize: { default: "64px", "@media (max-width: 780px)": "40px" },
    maxWidth: "12ch",
  },
  support: { fontSize: "18px", maxWidth: "42ch", marginTop: space.lg },
  actions: { display: "flex", gap: space.md, marginTop: space.xl, flexWrap: "wrap" },
  cta: {
    display: "inline-block",
    backgroundColor: { default: colors.ink, ":hover": "#000" },
    color: colors.paper,
    borderRadius: radii.sm,
    paddingBlock: "14px",
    paddingInline: space.lg,
    fontSize: "16px",
    fontWeight: 500,
    textDecorationLine: "none",
    outlineColor: colors.accent,
    outlineStyle: { default: "none", ":focus-visible": "solid" },
    outlineWidth: "2px",
    outlineOffset: "3px",
  },
  ctaGhost: {
    display: "inline-block",
    color: colors.ink,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.ruleStrong,
    borderRadius: radii.sm,
    paddingBlock: "12px",
    paddingInline: space.lg,
    fontSize: "16px",
    fontWeight: 500,
    fontFamily: type.sans,
    textDecorationLine: "none",
    backgroundColor: { default: "transparent", ":hover": colors.paperSunk },
    outlineColor: colors.accent,
    outlineStyle: { default: "none", ":focus-visible": "solid" },
    outlineWidth: "2px",
    outlineOffset: "3px",
  },
  section: {
    paddingBlock: { default: "88px", "@media (max-width: 780px)": space.xxl },
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: colors.rule,
  },
  sunk: { backgroundColor: colors.paperSunk },
  prose: {
    fontSize: { default: "18px", "@media (max-width: 780px)": "16px" },
    lineHeight: 1.7,
    maxWidth: "58ch",
    marginTop: space.lg,
  },
  shotFrame: {
    marginTop: space.xl,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.ruleStrong,
    borderRadius: radii.lg,
    overflow: "hidden",
    boxShadow: "0 18px 50px rgba(27, 24, 21, 0.10)",
  },
  shot: { display: "block", width: "100%", height: "auto" },
  caption: { marginTop: space.md },
  // Heading in a fixed left column, ruled term and definition rows on the right.
  block: {
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(0, 2fr) minmax(0, 3fr)",
      "@media (max-width: 780px)": "1fr",
    },
    gap: { default: "64px", "@media (max-width: 780px)": space.lg },
    alignItems: "start",
  },
  blockHeading: { maxWidth: "14ch" },
  rows: { margin: 0, display: "grid" },
  row: {
    display: "grid",
    gridTemplateColumns: { default: "200px minmax(0, 1fr)", "@media (max-width: 780px)": "1fr" },
    gap: { default: space.lg, "@media (max-width: 780px)": space.xs },
    paddingBlock: space.base,
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: colors.rule,
  },
  term: { fontFamily: type.serif, fontSize: "20px", fontWeight: 600, margin: 0 },
  definition: { margin: 0, maxWidth: "48ch" },
  /* The specimen: one real decision rendered as live HTML, not a screenshot. */
  card: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.ruleStrong,
    borderRadius: radii.lg,
    backgroundColor: colors.card,
    boxShadow: "0 14px 40px rgba(27, 24, 21, 0.08)",
    overflow: "hidden",
  },
  cardHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    gap: space.md,
    paddingBlock: space.md,
    paddingInline: space.lg,
    backgroundColor: colors.paperSunk,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.rule,
  },
  cardBody: { paddingBlock: space.lg, paddingInline: space.lg, display: "grid", gap: space.base },
  cardTitle: { display: "flex", alignItems: "center", gap: space.md },
  field: { display: "grid", gap: "4px" },
  fieldValue: { maxWidth: "58ch" },
  cardMeta: {
    display: "flex",
    gap: space.base,
    flexWrap: "wrap",
    fontFamily: type.sans,
    fontSize: type.small,
    color: colors.inkMuted,
  },
  cardStatus: { fontSize: type.label, letterSpacing: "0.08em", textTransform: "uppercase" },
  active: { color: colors.active },
  superseded: { color: colors.superseded },
  reversed: { color: colors.reversed },
  cardHistory: {
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: colors.rule,
    paddingBlock: space.base,
    paddingInline: space.lg,
    display: "grid",
    gap: space.sm,
    backgroundColor: colors.paper,
  },
  cardEvent: {
    display: "grid",
    gridTemplateColumns: { default: "150px 1fr", "@media (max-width: 780px)": "1fr" },
    gap: space.md,
  },
  arrow: { color: colors.inkFaint },
  footer: {
    paddingBlock: space.xl,
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: colors.rule,
  },
});

/** Both calls to action point at the same place. */
export const DEMO_HREF = "./demo.html";
