import * as stylex from "@stylexjs/stylex";
import { colors, radii, space, type } from "@/tokens.stylex";

export const styles = stylex.create({
  actions: { display: "flex", alignItems: "center", gap: space.sm },
  // Matches the close control, so the header keeps one height across modes.
  edit: { height: "34px", paddingBlock: 0, fontSize: type.small },
  close: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "34px",
    height: "34px",
    padding: 0,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: { default: "transparent", ":hover": colors.ruleStrong },
    borderRadius: radii.md,
    backgroundColor: { default: "transparent", ":hover": colors.paperSunk },
    color: { default: colors.inkMuted, ":hover": colors.ink },
    cursor: "pointer",
    outlineColor: colors.accent,
    outlineStyle: { default: "none", ":focus-visible": "solid" },
    outlineWidth: "2px",
    outlineOffset: "2px",
  },
  heading: { marginTop: space.md },
  list: {
    display: "grid",
    gridTemplateColumns: { default: "96px 1fr", "@media (max-width: 780px)": "1fr" },
    columnGap: space.lg,
    rowGap: space.md,
    margin: 0,
    marginTop: space.lg,
  },
  term: { paddingTop: "3px" },
  definition: { margin: 0 },
  section: {
    marginTop: space.xl,
    paddingTop: space.base,
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: colors.rule,
  },
  segment: {
    display: "inline-flex",
    marginTop: space.sm,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.ruleStrong,
    borderRadius: radii.md,
    overflow: "hidden",
  },
  option: {
    borderWidth: 0,
    borderRightWidth: "1px",
    borderRightStyle: "solid",
    borderRightColor: colors.rule,
    borderRadius: 0,
    backgroundColor: { default: "transparent", ":hover": colors.paperSunk },
    color: colors.inkMuted,
    fontWeight: 400,
    ":last-child": { borderRightWidth: 0 },
  },
  chosen: {
    backgroundColor: { default: colors.ink, ":hover": colors.ink },
    color: colors.paper,
    fontWeight: 500,
  },
  hint: { marginTop: space.md },
  history: { marginTop: space.md, display: "grid", gap: space.base },
  event: { display: "grid", gap: "2px" },
  when: { fontVariantNumeric: "tabular-nums" },
  move: { paddingLeft: space.md },
  detail: { color: colors.inkMuted },
  arrow: { color: colors.inkFaint },
});
