import * as stylex from "@stylexjs/stylex";
import { colors, radii, space, type } from "../../tokens.stylex";

/** PROTOTYPE. Throwaway styles shared by the landing variants. */

const narrow = "@media (max-width: 900px)";

export const p = stylex.create({
  page: { backgroundColor: colors.paper, color: colors.ink },
  wide: {
    maxWidth: "1160px",
    marginInline: "auto",
    paddingInline: { default: space.lg, [narrow]: space.base },
  },
  wrap: {
    maxWidth: "760px",
    marginInline: "auto",
    paddingInline: { default: space.lg, [narrow]: space.base },
  },
  section: {
    paddingBlock: { default: "80px", [narrow]: space.xxl },
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: colors.rule,
  },
  sunk: { backgroundColor: colors.paperSunk },
  cta: {
    display: "inline-block",
    backgroundColor: { default: colors.ink, ":hover": "#000" },
    color: colors.paper,
    borderRadius: radii.sm,
    paddingBlock: "13px",
    paddingInline: space.lg,
    fontSize: "16px",
    fontWeight: 500,
    textDecorationLine: "none",
    fontFamily: type.sans,
  },
  ctaGhost: {
    display: "inline-block",
    color: colors.ink,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.ruleStrong,
    borderRadius: radii.sm,
    paddingBlock: "12px",
    paddingInline: space.lg,
    fontSize: "16px",
    fontWeight: 500,
    textDecorationLine: "none",
    fontFamily: type.sans,
    backgroundColor: { default: "transparent", ":hover": colors.paperSunk },
  },
  prose: {
    fontSize: { default: "18px", [narrow]: "16px" },
    lineHeight: 1.7,
    maxWidth: "58ch",
    marginTop: space.lg,
  },
  serifLead: {
    fontFamily: type.serif,
    fontSize: { default: "24px", [narrow]: "20px" },
    lineHeight: 1.45,
    maxWidth: "36ch",
  },

  /* A: specimen hero */
  aHero: {
    display: "grid",
    gridTemplateColumns: { default: "minmax(0, 5fr) minmax(0, 6fr)", [narrow]: "1fr" },
    gap: { default: "72px", [narrow]: space.xl },
    alignItems: "center",
    paddingTop: { default: "96px", [narrow]: space.xxl },
    paddingBottom: { default: "96px", [narrow]: space.xl },
  },
  aHeadline: { fontSize: { default: "64px", [narrow]: "40px" }, maxWidth: "12ch" },
  aSupport: { fontSize: "18px", maxWidth: "42ch", marginTop: space.lg },
  aActions: { display: "flex", gap: space.md, marginTop: space.xl, flexWrap: "wrap" },
  aNote: { marginTop: space.md, maxWidth: "40ch" },
  aTwoCol: {
    display: "grid",
    gridTemplateColumns: { default: "1fr 1fr", [narrow]: "1fr" },
    gap: { default: "64px", [narrow]: space.xl },
    marginTop: space.xl,
  },

  aBlock: {
    display: "grid",
    gridTemplateColumns: { default: "minmax(0, 2fr) minmax(0, 3fr)", [narrow]: "1fr" },
    gap: { default: "64px", [narrow]: space.lg },
    alignItems: "start",
    paddingBlock: { default: space.xl, [narrow]: space.lg },
    borderTopWidth: { default: 0, ":not(:first-child)": "1px" },
    borderTopStyle: "solid",
    borderTopColor: colors.rule,
  },
  aBlockHeading: { maxWidth: "14ch" },
  aRows: { margin: 0, display: "grid" },
  aRow: {
    display: "grid",
    gridTemplateColumns: { default: "200px minmax(0, 1fr)", [narrow]: "1fr" },
    gap: { default: space.lg, [narrow]: space.xs },
    paddingBlock: space.base,
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: colors.rule,
  },
  aRowDef: { margin: 0, maxWidth: "48ch" },

  /* Specimen card, used by A and B */
  card: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.ruleStrong,
    borderRadius: radii.lg,
    backgroundColor: colors.card,
    boxShadow: "0 14px 40px rgba(27, 24, 21, 0.08)",
    overflow: "hidden",
  },
  cardHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    gap: space.md,
    paddingBlock: space.md,
    paddingInline: space.lg,
    backgroundColor: colors.paperSunk,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.rule,
  },
  cardBody: { paddingBlock: space.lg, paddingInline: space.lg, display: "grid", gap: space.base },
  cardTitle: { display: "flex", alignItems: "center", gap: space.md },
  field: { display: "grid", gap: "4px" },
  fieldValue: { maxWidth: "58ch" },
  meta: {
    display: "flex",
    gap: space.base,
    flexWrap: "wrap",
    fontFamily: type.sans,
    fontSize: type.small,
    color: colors.inkMuted,
  },
  status: { fontSize: type.label, letterSpacing: "0.08em", textTransform: "uppercase" },
  active: { color: colors.active },
  superseded: { color: colors.superseded },
  reversed: { color: colors.reversed },
  history: {
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: colors.rule,
    paddingBlock: space.base,
    paddingInline: space.lg,
    display: "grid",
    gap: space.sm,
    backgroundColor: colors.paper,
  },
  event: { display: "grid", gridTemplateColumns: "150px 1fr", gap: space.md },
  arrow: { color: colors.inkFaint },
  faded: { opacity: 0.55 },

  /* B: one decision, read later */
  bHero: { paddingTop: { default: "110px", [narrow]: space.xxl }, paddingBottom: space.xl },
  bHeadline: { maxWidth: "14ch" },
  bLayout: {
    display: "grid",
    gridTemplateColumns: { default: "minmax(0, 1fr) 280px", [narrow]: "1fr" },
    gap: { default: "80px", [narrow]: space.xl },
    alignItems: "start",
  },
  bRail: {
    position: { default: "sticky", [narrow]: "static" },
    top: "32px",
    display: "grid",
    gap: space.base,
    paddingTop: space.md,
  },
  bStep: {
    display: "grid",
    gridTemplateColumns: { default: "170px minmax(0, 1fr)", [narrow]: "1fr" },
    gap: { default: space.xl, [narrow]: space.md },
    paddingBlock: space.xl,
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: colors.rule,
  },
  bWhen: {
    fontFamily: type.serif,
    fontSize: "20px",
    fontWeight: 600,
    lineHeight: 1.3,
  },
  bWhenSub: { marginTop: space.xs },
  bRow: {
    display: "grid",
    gridTemplateColumns: { default: "minmax(0, 1fr) 150px", [narrow]: "1fr" },
    gap: space.base,
    paddingBlock: space.base,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: colors.rule,
  },
  bPair: { marginTop: space.base },
  bQuote: {
    fontFamily: type.serif,
    fontSize: "22px",
    lineHeight: 1.4,
    fontStyle: "italic",
    color: colors.inkMuted,
    maxWidth: "34ch",
  },

  /* C: the log is the page */
  cTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: space.lg,
    paddingBlock: space.lg,
    flexWrap: "wrap",
  },
  cBrand: { fontFamily: type.serif, fontSize: "20px", fontWeight: 600 },
  cHero: {
    display: "grid",
    gridTemplateColumns: { default: "minmax(0, 1fr) 320px", [narrow]: "1fr" },
    gap: { default: "64px", [narrow]: space.lg },
    alignItems: "end",
    paddingTop: { default: space.xxl, [narrow]: space.xl },
    paddingBottom: space.xl,
  },
  cHeadline: { fontSize: { default: "56px", [narrow]: "38px" }, maxWidth: "16ch" },
  cLogWrap: {
    display: "grid",
    gridTemplateColumns: { default: "minmax(0, 1fr) 240px", [narrow]: "1fr" },
    gap: { default: space.xl, [narrow]: space.lg },
    alignItems: "start",
    paddingBottom: "80px",
  },
  cLogBox: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: colors.ruleStrong,
    borderRadius: radii.lg,
    backgroundColor: colors.card,
    overflow: "hidden",
    boxShadow: "0 18px 50px rgba(27, 24, 21, 0.10)",
  },
  cLogBody: {
    display: "grid",
    gridTemplateColumns: { default: "190px 1fr", [narrow]: "1fr" },
    alignItems: "start",
  },
  cLogFoot: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: space.md,
    flexWrap: "wrap",
    paddingBlock: space.md,
    paddingInline: space.lg,
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: colors.rule,
    backgroundColor: colors.paperSunk,
  },
  cNotes: {
    position: { default: "sticky", [narrow]: "static" },
    top: "32px",
    display: "grid",
    gap: space.lg,
    paddingTop: space.sm,
  },
  cNote: {
    borderLeftWidth: "0",
    paddingLeft: 0,
    display: "grid",
    gap: "4px",
  },
  cGrid: {
    display: "grid",
    gridTemplateColumns: { default: "1fr 1fr", [narrow]: "1fr" },
    gap: { default: "48px 64px", [narrow]: space.xl },
    marginTop: space.xl,
  },
  strong: { fontWeight: 500 },
  cTerm: { fontFamily: type.serif, fontSize: "20px", fontWeight: 600 },
  cDef: { marginTop: space.xs, maxWidth: "44ch" },
  footer: {
    paddingBlock: space.xl,
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: colors.rule,
  },
});
